### ISSUE TITLE
SMALL_APP_LOG?

### ISSUE THREAD

**Issue by evbo** [Canop/cli-log#1]
Please explain `SMALL_APP_LOG` in your docs I have no idea where that comes from. Is it some kind of pattern based on the Cargo.toml app name?

if my app is named "foo" will I need to set `FOO_LOG`? 

thanks and even just a single sentence is fine to explain it.

**Comment by evbo** [comment]
also note it's not obvious what this env var should be named if there are dashes in the app name

**Comment by Canop** [comment]
> if my app is named "foo" will I need to set FOO_LOG?

Yes

> also note it's not obvious what this env var should be named if there are dashes in the app name

Good point. I'll handle that.
